# ---- ENVIRONMENTS ---- #

:http = http
:host = localhost:3000
:appkey = key
:api = :http://:host
:token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIiA6ICJ3ZWJ1c2VyIiwgInVzZXJfaWQiIDogMSwgImV4cCIgOiAxNTk1NTgwNTIxfQ.FDUayguywSMa9d1XuynOm1LsXIF2Sg_CGljW2HxsMtI

# :header = <<
# apikey: :appkey
# Content-Type: application/json
#
#
:header = <<
apikey: :appkey
User-Agent: restclient/2.0
Content-Type: application/json

#header with token
:headerT = <<
:header
Authorization: Bearer :token


#GET PING
GET :api/
:header


#GET LOGin
POST :api/rpc/login
:header
{
  "email": "alice@email.com",
  "password": "pass",
  "jwt_cookie": false,
  "rt_cookie": true,
  "csrf": false
}

#GET TODO
GET :api/todos
:headerT


#GET TODO
GET :api/sessions
:header


#GET TODO
GET :api/todos?id=eq.1
:headerT


#GET TODO
GET :api/todos?id=eq.2
:headerT

#GET TODO
GET :api/todos?limit=1
:headerT


#GET TODO2
GET :api/todos
:headerT
Accept: text/csv
